### ISSUE TITLE
`@Model` DB Related Directives

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/api#21]
There are a number of directives from #13 that cannot be implemented until #5 is implemented. See the `epic:db` label.

- [x] Implement basics of `@Model`
  - [x] Implement `dbConfig` for `ModelOption`
  - [x] inject create (instance)
  - [x] inject save (instance)
  - [x] inject delete (instance)
  - [x] inject get (static)
  - [x] inject getById (static)
  - [x] inject delete (static)
  - [x] make sure CRUD methods allow for mongodb options
  - [x] make sure get methods allow for mongodb field projection
  - [x] inject `fromDb` static method to instantiate a Model Object from a DB result
  - [x] inject `fromDbArray` static method to instantiate an array of Model Objects from DB results
  - [x] inject `toDb` static method
- [x] `@Required` -- see #36
- [x] `@Db`
  - [x] fromDb integration
  - [x] update CRUD to respect @Db
    - [x] crudCreate
    - [x] crudSave
    - [x] crudDelete
    - [x] crudGetStatic
    - [x] crudGetByIdStatic
  - [x] implement private field in @Db to prevent @Json from marshalling that field
  - [x] implement DbOptions or string parameter (the latter mapping to DbOptions.field)
- [ ] ~`@Validate`~ moved to #38 
- [x] Make sure you have all the debugs in place

**Comment by etsuo** [comment]
# `@Db({})`

```
import {SakuraApi} from 'sakuraapi';
import * as mongodb from 'mongodb';

const config = SakuraApi.instance.config;

class DataSources {
    static userDb = mongodb.MongoClient.connect(config.userDbUrl)
}
```

```
import {DataSources} from 'config/datasources';

@Model({
    dbConfig: {
        db: DataSources.userDb,
        collection: 'users'
    }
})
class User {
    @Db({
        field: '_id',
        type: ObjectId
    })
    id: string = '';    

    @Db({
        field: 'un',
        type: String,
        required: true,
        default: ''
    })
    @Json('un')
    userName: string = '';

    @Db({
        field: 'pw',
        type: String,
        required: true
    })
    @Private()
    userName: string = '';
}
```

**Comment by etsuo** [comment]
It is finished... I think.
