### ISSUE TITLE
Integrate `@Model` and `@Routable` for default API

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/api#6]
```
@Routable({
    baseUrl: 'use',
    model: User,
    suppressApi: ['delete']
})
class UserApi {
    @Route({
        method: 'get',
        model: UserVote
    })
    getSomethingElse() {
    }
}
```
The idea here is that `@Routable` will take a optional model property which can be any Class that's decorated with `@Model`. If a model is provided, by default, the `@Routable` class will support:
- GET model
- GET model/{id}
- PUT model (with the change set being in the body and the change set requiring an id property)
- PUT model 
- DELETE model

Since the `@Routable` optional `suppressApi` property has the string `delete` provided in its array, a route for DELETE model/ will not be created.

Alternatively, `exposeApi` also takes an array of strings, but it defaults to all APIs being suppressed except those explicitly exposed.

APIs include:

- [x] - get [GET /{:id}], returns an object
- [x] - get [GET /{:id}?filter={}], returns an object
- [x] - getAll [GET], return array of objects
   - [x] basic functionality
   - [x] ?where={}
   - [x] ?fields={} // exclude / include certain fields
      - [x] - fromDb strict mode support for projection
      - [x] - toJson support for projection
   - [x] ?skip=# // skip x results
   - [x] ?limit=# // limit to x results
   - [x] ~~prevent NoSQL injection~~ (moved to #65)
- [x] - put [PUT /{:id}], takes a change set with id and updates a document
- [x] - post [POST], takes an object and creates the document
- [x] - delete [DELETE /{:id}, deletes a document
- [x] - mapJsonToDb static function on model

**Comment by etsuo** [comment]
See also #13

**Comment by etsuo** [comment]
```
@Routable({
    baseUrl: 'use',
    model: User,
    suppressApi: ['delete']
})
class UserApi {
    @Route({
        method: 'get',
        model: UserVote
    })
    getSomethingElse() {
    }
}
```
The idea here is that `@Routable` will take a optional model property which can be any Class that's decorated with `@Model`. If a model is provided, by default, the `@Routable` class will support:
- GET model
- GET model/{id}
- PUT model (with the change set being in the body and the change set requiring an id property)
- PUT model 
- DELETE model

Since the `@Routable` optional `suppressApi` property has the string `delete` provided in its array, a route for DELETE model/ will not be created.

Alternatively, `exposeApi` also takes an array of strings, but it defaults to all APIs being suppressed except those explicitly exposed.

APIs include:

- [ ] - get [GET /{:id}], returns an object
- [ ] - getAll [GET], return array of objects
- [ ] - put [PUT /{:id}], takes a change set with id and updates a document
- [ ] - post [POST], takes an object and creates the document
- [ ] - delete [DELETE /{:id}, deletes a document
